In [1]:
import pandas as pd
import sqlite3

# 1. Tera Dummy Data (Pandas mein)
data = {
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Vikas'],
    'Course': ['Steno', 'Typing', 'Steno', 'Steno', 'Typing'],
    'Typing_Speed': [35, 55, 45, 60, 42]
}
df_students = pd.DataFrame(data)

# 2. Jupyter ke andar SQL Database banana (Cheat Code)
conn = sqlite3.connect(':memory:') # RAM mein temporary database banaya
df_students.to_sql('Students_Data', conn, index=False) # Pandas data ko SQL table mein daal diya

# 3. TERA SQL QUERY (Triple quotes mein likhte hain Python mein)
query = """
SELECT Name, Typing_Speed
FROM Students_Data
WHERE Course = 'Steno' AND Typing_Speed > 40
ORDER BY Typing_Speed DESC;
"""

# 4. Result dekhna
result = pd.read_sql(query, conn)
print(result)

    Name  Typing_Speed
0   Neha            60
1  Rahul            45

# installing sql into pandas using this below code

In [2]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\vishal parmar\anaconda34\lib\site-packages (from pandasql) (1.24.3)
Requirement already satisfied: pandas in c:\users\vishal parmar\anaconda34\lib\site-packages (from pandasql) (2.0.3)
Requirement already satisfied: sqlalchemy in c:\users\vishal parmar\anaconda34\lib\site-packages (from pandasql) (1.4.39)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishal parmar\anaconda34\lib\site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vishal parmar\anaconda34\lib\site-packages (from pandas->pandasql) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\vishal parmar\anaconda34\lib\site-packages (from pandas->pandasql) (2023.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\vishal parmar\anaconda34\lib\site-packages (from sqlalchemy->pandasql) (2.0.1)
Requirement already satisfied: six>=1.5 in c:\users\vishal parmar\anaconda34\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py): started
  Building wheel for pandasql (setup.py): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26800 sha256=5fccc8d99ab316311131ebcffa18f624e449da596df8ed6ba3865bb67486efff
  Stored in directory: c:\users\vishal parmar\appdata\local\pip\cache\wheels\68\5d\a5\edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [6]:
from pandasql import sqldf

# Bas apna SQL likh (Dataframe ka naam hi table ka naam ban jayega)
query = """
SELECT Name, Typing_Speed
FROM df_students
WHERE Course = 'Typing' AND Typing_Speed < 50
"""

# Seedha Run
sqldf(query)

    Name  Typing_Speed
0  Vikas            42

In [14]:
queryy="""
SELECT Name, Course, Typing_Speed
FROM df_students
WHERE Course='Typing' AND Typing_Speed<50
ORDER BY Typing_Speed ASC
"""
sqldf(queryy)

    Name  Course  Typing_Speed
0  Vikas  Typing            42

In [8]:
query1 = """
SELECT Name, Course, Typing_Speed
FROM df_students
WHERE Course = 'Typing' AND Typing_Speed < 50
ORDER BY Typing_Speed ASC;
"""

sqldf(query1)

    Name  Course  Typing_Speed
0  Vikas  Typing            42

In [11]:
query2="""
SELECT Name,Course,Typing_Speed
FROM df_students
WHERE Course='Typing' and Typing_Speed<50
ORDER BY Typing_Speed ASC;
"""
sqldf(query2)

    Name  Course  Typing_Speed
0  Vikas  Typing            42

In [15]:
query3 = """
SELECT Course, AVG(Typing_Speed) AS Average_Speed
FROM df_students
GROUP BY Course;
"""

sqldf(query3)

   Course  Average_Speed
0   Steno      46.666667
1  Typing      48.500000

In [17]:
query4="""
SELECT Name,Course,Typing_Speed,Typing_Speed+15 AS Target_Speed
FROM df_students
WHERE Course='Steno'
"""
sqldf(query4)

    Name Course  Typing_Speed  Target_Speed
0   Amit  Steno            35            50
1  Rahul  Steno            45            60
2   Neha  Steno            60            75

In [18]:
query5="""
SELECT Name,Course, Typing_Speed
FROM df_students
ORDER BY Typing_Speed DESC
LIMIT 2
"""
sqldf(query5)

    Name  Course  Typing_Speed
0   Neha   Steno            60
1  Priya  Typing            55

In [1]:
SELECT Course, AVG(Typing_Speed)
FROM df_students
GROUP BY Course
HAVING AVG(Typing_Speed) > 40;

SyntaxError: invalid syntax (1002957788.py, line 1)

In [2]:
import pandas as pd
from pandasql import sqldf

data = {
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Vikas'],
    'Course': ['Steno', 'Typing', 'Steno', 'Steno', 'Typing'],
    'Typing_Speed': [35, 55, 45, 60, 42],
    'Fees_Paid': ['No', 'Yes', 'Yes', 'Yes', 'No']
}
df_students = pd.DataFrame(data)

In [3]:
df_students

   Student_ID   Name  Course  Typing_Speed Fees_Paid
0         101   Amit   Steno            35        No
1         102  Priya  Typing            55       Yes
2         103  Rahul   Steno            45       Yes
3         104   Neha   Steno            60       Yes
4         105  Vikas  Typing            42        No

In [6]:
query7="""
SELECT Course,AVG(Typing_Speed) AS Typing_Speed
FROM df_students
GROUP BY Course
HAVING AVG(Typing_Speed)>47
"""
sqldf(query7)

   Course  Typing_Speed
0  Typing          48.5

In [7]:
query_fixed = """
SELECT Course, AVG(Typing_Speed) AS Avg_Speed
FROM df_students
GROUP BY Course
HAVING AVG(Typing_Speed) > 47;
"""

sqldf(query_fixed)

   Course  Avg_Speed
0  Typing       48.5

In [8]:
query_multi = """
SELECT 
    Course, 
    AVG(Typing_Speed) AS Avg_Speed,
    MAX(Typing_Speed) AS Highest_Speed,
    MIN(Typing_Speed) AS Lowest_Speed
FROM df_students
GROUP BY Course;
"""

sqldf(query_multi)

   Course  Avg_Speed  Highest_Speed  Lowest_Speed
0   Steno  46.666667             60            35
1  Typing  48.500000             55            42

In [9]:
import pandas as pd
from pandasql import sqldf

# Table 1: Jaya Institute Students Info
data_info = {
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Course': ['Steno', 'Typing', 'Steno', 'Typing']
}
df_info = pd.DataFrame(data_info)

# Table 2: Jaya Institute Fees Info
data_fees = {
    'Student_ID': [101, 102, 104, 105], # Notice kar: 103 ka record yahan nahi hai, aur 105 naya hai
    'Amount_Paid': [5000, 4500, 6000, 4000]
}
df_fees = pd.DataFrame(data_fees)

In [10]:
query8="""
SELECT Name,Course,Amount_Paid
FROM df_info
JOIN df_fees
ON df_info.Student_ID=df_fees.Student_ID
"""
sqldf(query8)

    Name  Course  Amount_Paid
0   Amit   Steno         5000
1  Priya  Typing         4500
2   Neha  Typing         6000

In [11]:
query9="""
SELECT Name, Course, Amount_Paid
FROM df_info
LEFT JOIN df_fees
ON df_info.Student_ID=df_fees.Student_ID
"""
sqldf(query9)

    Name  Course  Amount_Paid
0   Amit   Steno       5000.0
1  Priya  Typing       4500.0
2  Rahul   Steno          NaN
3   Neha  Typing       6000.0

In [12]:
import pandas as pd
from pandasql import sqldf

# Table 1: Students Master Data
st_data = {
    'Student_ID': range(101, 116),
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Vikas', 'Sonia', 'Rohan', 'Kiran', 'Pooja', 'Aman', 'Karan', 'Sneha', 'Mohit', 'Simran', 'Raj'],
    'Course': ['Steno', 'Typing', 'Steno', 'Typing', 'Typing', 'Steno', 'Typing', 'Steno', 'Typing', 'Steno', 'Typing', 'Steno', 'Typing', 'Steno', 'Typing'],
    'Typing_Speed': [35, 55, 45, 60, 42, 38, 65, 40, 50, 30, 48, 52, 36, 44, 58],
    'Age': [19, 21, 20, 22, 18, 23, 20, 19, 21, 24, 18, 22, 20, 21, 19]
}
df_students = pd.DataFrame(st_data)

# Table 2: Fees Transaction Data
fee_data = {
    'Student_ID': [101, 102, 103, 104, 106, 107, 108, 109, 111, 112, 114, 115, 120], # Notice: Some IDs are missing (defaulters)
    'Amount_Paid': [5000, 4500, 2000, 6000, 5000, 4500, 2500, 4500, 4000, 5000, 3000, 4500, 5000],
    'Status': ['Full', 'Full', 'Half', 'Full', 'Full', 'Full', 'Half', 'Full', 'Half', 'Full', 'Half', 'Full', 'Full']
}
df_fees = pd.DataFrame(fee_data)

In [17]:
q2="""
SELECT Name, Age,Course
FROM df_students
ORDER BY Age DESC
LIMIT 3
"""
sqldf(q2)

    Name  Age  Course
0   Aman   24   Steno
1  Sonia   23   Steno
2   Neha   22  Typing

In [20]:
q3="""
SELECT  AVG(Age) as AGE, Course
FROM df_students
GROUP BY Course
ORDER BY AVG(Age)
"""
sqldf(q3)

         AGE  Course
0  19.875000  Typing
1  21.142857   Steno

In [22]:
q4="""
SELECT Course,MIN(Typing_Speed) as Typing_Speed
FROM df_students
GROUP BY Course
HAVING MIN(Typing_Speed)<35
ORDER BY MIN(Typing_Speed) DESC
"""
sqldf(q4)

  Course  Typing_Speed
0  Steno            30

In [24]:
q5="""
SELECT Name, Course, Status
FROM df_students
JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
"""
sqldf(q5)

      Name  Course Status
0     Amit   Steno   Full
1    Priya  Typing   Full
2    Rahul   Steno   Half
3     Neha  Typing   Full
4    Sonia   Steno   Full
5    Rohan  Typing   Full
6    Kiran   Steno   Half
7    Pooja  Typing   Full
8    Karan  Typing   Half
9    Sneha   Steno   Full
10  Simran   Steno   Half
11     Raj  Typing   Full

In [31]:
q6="""
SELECT Course, SUM(Amount_Paid) AS Total_Revenue
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
GROUP BY Course
ORDER BY SUM(Amount_Paid) DESC
"""
sqldf(q6)

   Course  Total_Revenue
0  Typing          28000
1   Steno          22500

In [51]:
q7="""
SELECT Name,Course,Amount_Paid
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Amount_Paid IS NULL
"""
sqldf(q7)

    Name  Course Amount_Paid
0  Vikas  Typing        None
1   Aman   Steno        None
2  Mohit  Typing        None

In [34]:
q8="""
SELECT Name,Course,Status
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Course='Steno' and Status='Half'
"""
sqldf(q8)

     Name Course Status
0   Rahul  Steno   Half
1   Kiran  Steno   Half
2  Simran  Steno   Half

In [36]:
q9="""
SELECT Name,Course,Status
FROM df_students
JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
"""
sqldf(q9)

      Name  Course Status
0     Amit   Steno   Full
1    Priya  Typing   Full
2    Rahul   Steno   Half
3     Neha  Typing   Full
4    Sonia   Steno   Full
5    Rohan  Typing   Full
6    Kiran   Steno   Half
7    Pooja  Typing   Full
8    Karan  Typing   Half
9    Sneha   Steno   Full
10  Simran   Steno   Half
11     Raj  Typing   Full

In [40]:
q10="""
SELECT Count(Student_ID) AS Number_OF_Count,Status
FROM df_fees
GROUP BY Status
"""
sqldf(q10)

   Number_OF_Count Status
0                9   Full
1                4   Half

In [50]:
q11="""
SELECT Name,Typing_Speed,Status,Course
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Course='Typing' and Status='Full'
ORDER BY Typing_Speed DESC
"""
sqldf(q11)

    Name  Typing_Speed Status  Course
0  Rohan            65   Full  Typing
1   Neha            60   Full  Typing
2    Raj            58   Full  Typing
3  Priya            55   Full  Typing
4  Pooja            50   Full  Typing

In [54]:
df_students

    Student_ID    Name  Course  Typing_Speed  Age
0          101    Amit   Steno            35   19
1          102   Priya  Typing            55   21
2          103   Rahul   Steno            45   20
3          104    Neha  Typing            60   22
4          105   Vikas  Typing            42   18
5          106   Sonia   Steno            38   23
6          107   Rohan  Typing            65   20
7          108   Kiran   Steno            40   19
8          109   Pooja  Typing            50   21
9          110    Aman   Steno            30   24
10         111   Karan  Typing            48   18
11         112   Sneha   Steno            52   22
12         113   Mohit  Typing            36   20
13         114  Simran   Steno            44   21
14         115     Raj  Typing            58   19

In [55]:
df_fees

    Student_ID  Amount_Paid Status
0          101         5000   Full
1          102         4500   Full
2          103         2000   Half
3          104         6000   Full
4          106         5000   Full
5          107         4500   Full
6          108         2500   Half
7          109         4500   Full
8          111         4000   Half
9          112         5000   Full
10         114         3000   Half
11         115         4500   Full
12         120         5000   Full

In [52]:
q12="""
SELECT Course, Name, Status, Age
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Age>=21 and Status='Half'
"""
sqldf(q12)

  Course    Name Status  Age
0  Steno  Simran   Half   21

In [57]:
q13="""
SELECT AVG(Typing_speed) AS Average_speed,Status
FROM df_students
JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
GROUP BY Status
"""
sqldf(q13)

   Average_speed Status
0         51.625   Full
1         44.250   Half

In [60]:
df_fees

    Student_ID  Amount_Paid Status
0          101         5000   Full
1          102         4500   Full
2          103         2000   Half
3          104         6000   Full
4          106         5000   Full
5          107         4500   Full
6          108         2500   Half
7          109         4500   Full
8          111         4000   Half
9          112         5000   Full
10         114         3000   Half
11         115         4500   Full
12         120         5000   Full

In [62]:
q14="""
SELECT Course,SUM(Amount_Paid) AS Total_Revenue
FROM df_students
JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
GROUP BY Course
ORDER BY SUM(Amount_Paid) DESC
LIMIT 1
"""
sqldf(q14)

   Course  Total_Revenue
0  Typing          28000

In [64]:
q15="""
SELECT Status,AVG(Typing_Speed) AS Average_Speed
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Status IS NULL
ORDER BY AVG(Typing_Speed) DESC
"""
sqldf(q15)

  Status  Average_Speed
0   None           36.0

In [66]:
q16="""
SELECT Name,Age,Amount_Paid,Course
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Course='Steno'
ORDER BY Age ASC
"""
sqldf(q16)

     Name  Age  Amount_Paid Course
0    Amit   19       5000.0  Steno
1   Kiran   19       2500.0  Steno
2   Rahul   20       2000.0  Steno
3  Simran   21       3000.0  Steno
4   Sneha   22       5000.0  Steno
5   Sonia   23       5000.0  Steno
6    Aman   24          NaN  Steno

In [94]:
q116="""
SELECT Name, Course, Amount_Paid
FROM df_students
JOIN df_fees ON df_students.Student_ID = df_fees.Student_ID
WHERE Amount_Paid > (SELECT AVG(Amount_Paid) FROM df_fees);
"""
sqldf(q116)

    Name  Course  Amount_Paid
0   Amit   Steno         5000
1  Priya  Typing         4500
2   Neha  Typing         6000
3  Sonia   Steno         5000
4  Rohan  Typing         4500
5  Pooja  Typing         4500
6  Sneha   Steno         5000
7    Raj  Typing         4500

In [68]:
q17="""
SELECT Name,Course,AVG(Amount_Paid) AS Highest_Payer
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
GROUP BY Course
ORDER BY AVG(Amount_Paid)
"""
sqldf(q17)

    Name  Course  Highest_Payer
0   Amit   Steno    3750.000000
1  Priya  Typing    4666.666667

In [78]:
qq="""
SELECT MAX(Amount_Paid) 
FROM df_fees
"""
sqldf

In [76]:
q18="""
SELECT Name,Course,AVG(Amount_Paid) AS Highest_Payer
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
GROUP BY Course
HAVING AVG(Amount_Paid)>4000
"""
sqldf(q18)

    Name  Course  Highest_Payer
0  Priya  Typing    4666.666667

In [82]:
q19="""
SELECT MAX(Typing_Speed)-MIN(Typing_Speed) AS Gap,Course
FROM df_students
WHERE Course='Typing'
"""
sqldf(q19)

   Gap  Course
0   29  Typing

In [84]:
q20="""
SELECT Name,Course,Typing_Speed
FROM df_students
WHERE Typing_Speed BETWEEN 48 AND 49
"""
sqldf(q20)

    Name  Course  Typing_Speed
0  Karan  Typing            48

In [95]:
q21="""
SELECT Status,Course,Count(df_students.Student_ID) as Num
FROM df_students
LEFT JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
WHERE Course='Steno' AND Amount_Paid IS NULL
"""
sqldf(q21)

  Status Course  Num
0   None  Steno    1

In [96]:
q22="""
SELECT Course, Count(df_fees.Student_ID) as Count,AVG(Typing_Speed) as speed, SUM(Amount_Paid) as total_paid 
FROM df_students
JOIN df_fees
ON df_students.Student_ID=df_fees.Student_ID
GROUP BY Course
"""
sqldf(q22)

   Course  Count      speed  total_paid
0   Steno      6  42.333333       22500
1  Typing      6  56.000000       28000

# Topic: SQL CASE WHEN (Conditional Logic)

In [1]:
import pandas as pd
from pandasql import sqldf

# Creating the Students Dataframe
data_students = {
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Vikas'],
    'Course': ['Steno', 'Typing', 'Steno', 'Typing', 'Typing'],
    'Age': [19, 20, 20, 21, 19],
    'Typing_Speed': [35, 55, 40, 60, 45]
}
df_students = pd.DataFrame(data_students)

# Creating the Fees Dataframe
data_fees = {
    'Student_ID': [101, 102, 103, 104, 106],
    'Amount_Paid': [5000, 2500, 2000, 5000, 3000],
    'Status': ['Full', 'Half', 'Half', 'Full', 'Half']
}
df_fees = pd.DataFrame(data_fees)

In [2]:
df_students

   Student_ID   Name  Course  Age  Typing_Speed
0         101   Amit   Steno   19            35
1         102  Priya  Typing   20            55
2         103  Rahul   Steno   20            40
3         104   Neha  Typing   21            60
4         105  Vikas  Typing   19            45

In [3]:
df_fees

   Student_ID  Amount_Paid Status
0         101         5000   Full
1         102         2500   Half
2         103         2000   Half
3         104         5000   Full
4         106         3000   Half

In [5]:
b="""
SELECT Name, Typing_Speed,
    CASE
        WHEN Typing_Speed>50 THEN 'Fast'
        WHEN Typing_Speed>=40 THEN 'Average'
        ELSE 'Slow'
    END AS Speed_Status
FROM df_students
"""
sqldf(b)

    Name  Typing_Speed Speed_Status
0   Amit            35         Slow
1  Priya            55         Fast
2  Rahul            40      Average
3   Neha            60         Fast
4  Vikas            45      Average

In [6]:
b1="""
WITH Full_Fees_CTE AS(
    SELECT Student_ID,Amount_Paid,Status
    FROM df_fees
    WHERE Status='Full'
)
SELECT * FROM Full_Fees_CTE
"""
sqldf(b1)

   Student_ID  Amount_Paid Status
0         101         5000   Full
1         104         5000   Full

In [8]:
b_final = """
-- Step 1: Create the Temporary CTE
WITH Full_Fees_CTE AS (
    SELECT Student_ID, Amount_Paid
    FROM df_fees
    WHERE Status = 'Full'
)

-- Step 2: Immediately use it in the Main Query
SELECT df_students.Name, Full_Fees_CTE.Amount_Paid
FROM df_students
JOIN Full_Fees_CTE 
ON df_students.Student_ID = Full_Fees_CTE.Student_ID
"""

sqldf(b_final)

   Name  Amount_Paid
0  Amit         5000
1  Neha         5000

In [9]:
c = """
SELECT Name, Course, Typing_Speed,
       ROW_NUMBER() OVER (PARTITION BY Course ORDER BY Typing_Speed DESC) AS Speed_Rank
FROM df_students
"""
sqldf(c)

    Name  Course  Typing_Speed  Speed_Rank
0  Rahul   Steno            40           1
1   Amit   Steno            35           2
2   Neha  Typing            60           1
3  Priya  Typing            55           2
4  Vikas  Typing            45           3

In [10]:
d = """
-- Step 1: CTE ke andar Window Function laga kar sabko rank do
WITH Ranked_Students AS (
    SELECT Name, Course, Typing_Speed,
           ROW_NUMBER() OVER (PARTITION BY Course ORDER BY Typing_Speed DESC) AS Number_Sticker
    FROM df_students
)

-- Step 2: Ab is CTE (Virtual Table) mein se sirf unko nikal jinka Sticker 1 hai
SELECT Name, Course, Typing_Speed
FROM Ranked_Students
WHERE Number_Sticker = 1;
"""
sqldf(d)

    Name  Course  Typing_Speed
0  Rahul   Steno            40
1   Neha  Typing            60

# Dense Rank Syntax of SQL

In [5]:
import pandas as pd
import scipy.stats as stats
import numpy as np
from pandasql import sqldf

jti_data = {
    'Student_Name': ['Rahul', 'Priya', 'Amit', 'Neha', 'Karan'],
    'Course': ['Stenography', 'DCA', 'Tally Prime', 'Stenography', 'DCA'],
    'Typing_Speed_WPM': [45, 30, 0, 55, 35],'Fees_Paid': [5000, 2500, 3000, 5000, 2000]
}
df11=pd.DataFrame(jti_data)

In [6]:
df11

  Student_Name       Course  Typing_Speed_WPM  Fees_Paid
0        Rahul  Stenography                45       5000
1        Priya          DCA                30       2500
2         Amit  Tally Prime                 0       3000
3         Neha  Stenography                55       5000
4        Karan          DCA                35       2000

###  Kal raat ka nanga sach yaad kar. Tujhe SQL mein saare baccho ka data dikhana hai, aur unko unki 'Fees_Paid' ke hisaab se RANK karna hai (Sabse zyada fees dene wala Rank 1). Same fees walo ko same rank milna chahiye, aur koi number skip nahi hona chahiye.
Exact SQL query bata. (Hint: OVER(ORDER BY ... DESC)).

In [7]:
q5="""
SELECT Student_Name, Fees_Paid, DENSE_RANK() OVER(ORDER BY Fees_Paid DESC) AS Rank 
FROM df11;
""" 
sqldf(q5)

  Student_Name  Fees_Paid  Rank
0        Rahul       5000     1
1         Neha       5000     1
2         Amit       3000     2
3        Priya       2500     3
4        Karan       2000     4