In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
data = {
    'Typing_Speed': [30, 45, 60, 25, 50, 65, 35, 55, 70, 20],
    'Accuracy_Per': [85, 90, 95, 80, 92, 98, 88, 94, 99, 75],
    'Passed_Exam': [0, 1, 1, 0, 1, 1, 0, 1, 1, 0]
}
df_jti = pd.DataFrame(data)

In [4]:
df_jti

   Typing_Speed  Accuracy_Per  Passed_Exam
0            30            85            0
1            45            90            1
2            60            95            1
3            25            80            0
4            50            92            1
5            65            98            1
6            35            88            0
7            55            94            1
8            70            99            1
9            20            75            0

In [5]:
X=df_jti.drop('Passed_Exam',axis=1)
y=df_jti['Passed_Exam']

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
scale=StandardScaler()
X_train_scaled=scale.fit_transform(X_train)
X_test_scaled=scale.transform(X_test)
final_model_linear=SVC(kernel='linear',C=1.0)
final_model_linear.fit(X_train_scaled,y_train)
final_model_rbf=SVC(kernel='rbf',C=1.0,gamma='scale')
final_model_rbf.fit(X_train_scaled,y_train)
pred_linear=final_model_linear.predict(X_test_scaled)
pred_rbf=final_model_rbf.predict(X_test_scaled)
print(f"the linear accuracy score is {accuracy_score(y_test,pred_linear)*100:.2f}%")
print(f"the rbf accuracy score is {accuracy_score(y_test,pred_rbf)*100:.2f}%")

the linear accuracy score is 100.00%
the rbf accuracy score is 100.00%

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_rbf))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

In [15]:
import pandas as pd

# JTI Staff Promotion Data
data1 = {
    'Age': [22, 28, 35, 42, 25, 31, 45, 29, 38, 24],
    'Typing_Speed': [40, 55, 65, 80, 45, 60, 85, 50, 70, 42],
    'Years_in_JTI': [1, 3, 5, 10, 2, 4, 12, 3, 7, 1],
    'Promoted': [0, 0, 1, 1, 0, 1, 1, 0, 1, 0]
}
df_staff = pd.DataFrame(data1)

In [16]:
df_staff

   Age  Typing_Speed  Years_in_JTI  Promoted
0   22            40             1         0
1   28            55             3         0
2   35            65             5         1
3   42            80            10         1
4   25            45             2         0
5   31            60             4         1
6   45            85            12         1
7   29            50             3         0
8   38            70             7         1
9   24            42             1         0

In [17]:
X=df_staff.drop('Promoted',axis=1)
y=df_staff['Promoted']

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
scale=StandardScaler()
X_train_scaled=scale.fit_transform(X_train)
X_test_scaled=scale.transform(X_test)
f_model_linear=SVC(kernel='linear',C=1.0)
f_model_linear.fit(X_train_scaled,y_train)
f_model_rbf=SVC(kernel='rbf',C=1.0,gamma='scale')
f_model_rbf.fit(X_train_scaled,y_train)
lin_pred=f_model_linear.predict(X_test_scaled)
rbf_pred=f_model_linear.predict(X_test_scaled)
print(f"the accuracy score of linear : {accuracy_score(y_test,lin_pred)*100:.2f}%")
print(f"the accuracy score of rbf: {accuracy_score(y_test,rbf_pred)*100:.2f}%")
print('classification report of linear: ',classification_report(y_test,lin_pred))
print('classification report of rbf:', classification_report (y_test,rbf_pred))

the accuracy score of linear : 100.00%
the accuracy score of rbf: 100.00%
classification report of linear:                precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

classification report of rbf:               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2