In [1]:
import pandas as pd
ecom=pd.read_csv("online_retail.csv")

In [2]:
ecom

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [3]:
 ecom['Total_revenue']=ecom['Quantity']*ecom['Price']

In [4]:
ecom

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total_revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.00
...,...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00

In [5]:
ecom.isnull().sum()

Invoice               0
StockCode             0
Description        4382
Quantity              0
InvoiceDate           0
Price                 0
Customer ID      243007
Country               0
Total_revenue         0
dtype: int64

In [6]:
ecom.rename(columns={'Customer ID': 'Customer_ID'}, inplace=True)

In [7]:
ecom.dropna(inplace=True)

In [8]:
ecom.isnull().sum()

Invoice          0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
Price            0
Customer_ID      0
Country          0
Total_revenue    0
dtype: int64

In [9]:
ecom.info()

<class 'pandas.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Invoice        824364 non-null  str
 1   StockCode      824364 non-null  str
 2   Description    824364 non-null  str
 3   Quantity       824364 non-null  int64
 4   InvoiceDate    824364 non-null  str
 5   Price          824364 non-null  float64
 6   Customer_ID    824364 non-null  float64
 7   Country        824364 non-null  str
 8   Total_revenue  824364 non-null  float64
dtypes: float64(3), int64(1), str(5)
memory usage: 62.9 MB

In [10]:
ecom['InvoiceDate'] = pd.to_datetime(ecom['InvoiceDate'])

In [11]:
ecom.info()

<class 'pandas.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Invoice        824364 non-null  str
 1   StockCode      824364 non-null  str
 2   Description    824364 non-null  str
 3   Quantity       824364 non-null  int64
 4   InvoiceDate    824364 non-null  datetime64[us]
 5   Price          824364 non-null  float64
 6   Customer_ID    824364 non-null  float64
 7   Country        824364 non-null  str
 8   Total_revenue  824364 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 62.9 MB

In [12]:
latest_date = ecom['InvoiceDate'].max()
print(latest_date)

2011-12-09 12:50:00

In [13]:
import datetime as dt
snapshot_date = latest_date + dt.timedelta(days=1)
print(snapshot_date)

2011-12-10 12:50:00

In [14]:
rfm=ecom.groupby('Customer_ID').agg({'InvoiceDate': 'max','Invoice': 'nunique','Total_revenue': 'sum'})

In [16]:
rfm.rename(columns={'InvoiceDate': 'Recency_Date','Invoice': 'Frequency','Total_revenue': 'Monetary'},inplace=True)

In [17]:
rfm.head(2)

                   Recency_Date  Frequency  Monetary
Customer_ID
12346.0     2011-01-18 10:17:00         17    -64.68
12347.0     2011-12-07 15:52:00          8   5633.32

In [18]:
rfm.info()

<class 'pandas.DataFrame'>
Index: 5942 entries, 12346.0 to 18287.0
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Recency_Date  5942 non-null   datetime64[us]
 1   Frequency     5942 non-null   int64
 2   Monetary      5942 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 185.7 KB

In [19]:
snapshot_date

Timestamp('2011-12-10 12:50:00')

In [20]:
rfm['Recency'] = (snapshot_date - rfm['Recency_Date']).dt.days

In [21]:
rfm

                   Recency_Date  Frequency  Monetary  Recency
Customer_ID
12346.0     2011-01-18 10:17:00         17    -64.68      326
12347.0     2011-12-07 15:52:00          8   5633.32        2
12348.0     2011-09-25 13:13:00          5   2019.40       75
12349.0     2011-11-21 09:51:00          5   4404.54       19
12350.0     2011-02-02 16:01:00          1    334.40      310
...                         ...        ...       ...      ...
18283.0     2011-12-06 12:02:00         22   2736.65        4
18284.0     2010-10-06 12:31:00          2    436.68      430
18285.0     2010-02-17 10:24:00          1    427.00      661
18286.0     2010-08-20 11:57:00          3   1188.43      477
18287.0     2011-10-28 09:29:00          8   4177.89       43

[5942 rows x 4 columns]

In [22]:
rfm.drop(columns=['Recency_Date'], inplace=True)

In [23]:
rfm = rfm[['Recency', 'Frequency', 'Monetary']]

In [24]:
rfm.head(2)

             Recency  Frequency  Monetary
Customer_ID
12346.0          326         17    -64.68
12347.0            2          8   5633.32

In [25]:
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=4, labels=[4, 3, 2, 1])

In [26]:
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=4, labels=[1, 2, 3, 4])

In [27]:
rfm['M_Score'] = pd.qcut(rfm['Monetary'], q=4, labels=[1, 2, 3, 4])

In [28]:
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

In [29]:
rfm

             Recency  Frequency  Monetary R_Score F_Score M_Score RFM_Score
Customer_ID
12346.0          326         17    -64.68       2       4       1       241
12347.0            2          8   5633.32       4       3       4       434
12348.0           75          5   2019.40       3       3       3       333
12349.0           19          5   4404.54       4       3       4       434
12350.0          310          1    334.40       2       1       2       212
...              ...        ...       ...     ...     ...     ...       ...
18283.0            4         22   2736.65       4       4       4       444
18284.0          430          2    436.68       1       2       2       122
18285.0          661          1    427.00       1       1       2       112
18286.0          477          3   1188.43       1       2       3       123
18287.0           43          8   4177.89       3       4       4       344

[5942 rows x 7 columns]

In [30]:
def segment_customer(score_str):
    r = int(score_str[0])
    f = int(score_str[1])
    m = int(score_str[2])
    
    if r >= 3 and f >= 3 and m >= 3:
        return 'VIP / Champions'
    elif r >= 3 and f <= 2:
        return 'New & Potential'
    elif r <= 2 and f >= 3 and m >= 3:
        return 'At Risk (Loyal but leaving)'
    elif r <= 2 and f <= 2:
        return 'Lost Customers'
    else:
        return 'Regulars'

In [31]:
rfm['Customer_Segment'] = rfm['RFM_Score'].apply(segment_customer)

In [33]:
rfm['Customer_Segment'].value_counts()

Customer_Segment
Lost Customers                 2048
VIP / Champions                1852
New & Potential                 923
At Risk (Loyal but leaving)     668
Regulars                        451
Name: count, dtype: int64

## Executive Summary:

Analyzed a raw UK-based E-commerce dataset of 1 Million+ transaction records. Cleaned data anomalies (missing Customer IDs), engineered a 'Gross Revenue' feature, and developed a robust RFM (Recency, Frequency, Monetary) model using Pandas Quantile Cuts to segment ~6,000 unique customers.

## Conclusion (The Data Story):

The business is heavily polarized. While we have a strong core of 1,155 VIP/Champion customers driving consistent revenue, there is a massive churn issue with 1,782 Lost Customers. More critically, 756 customers are 'At Risk'—these are people who used to buy frequently and spend heavily, but haven't visited the store recently.

## The Business Solution (Actionable Strategies):

For VIPs / Champions: Introduce a premium "Loyalty Tier" with early access to new products. No heavy discounts needed; they value exclusivity.

For At-Risk (Loyal but leaving): This is where the marketing budget should go. Send highly personalized "We Miss You" emails with a strong, time-sensitive discount (e.g., 20% off) to reactivate them before they are lost forever.

For New & Potential: Trigger automated onboarding emails and cross-sell/upsell product recommendations based on their first purchase.

For Lost Customers: Stop spending marketing ad dollars on them. Move them to a low-cost, generic newsletter list.

In [34]:
rfm.to_csv('RFM_Final_Data.csv')

In [35]:
rfm

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Customer_Segment
Customer_ID,,,,,,,,
12346.0,326,17,-64.68,2,4,1,241,Regulars
12347.0,2,8,5633.32,4,3,4,434,VIP / Champions
12348.0,75,5,2019.40,3,3,3,333,VIP / Champions
12349.0,19,5,4404.54,4,3,4,434,VIP / Champions
12350.0,310,1,334.40,2,1,2,212,Lost Customers
...,...,...,...,...,...,...,...,...
18283.0,4,22,2736.65,4,4,4,444,VIP / Champions
18284.0,430,2,436.68,1,2,2,122,Lost Customers
18285.0,661,1,427.00,1,1,2,112,Lost Customers
18286.0,477,3,1188.43,1,2,3,123,Lost Customers
18287.0,43,8,4177.89,3,4,4,344,VIP / Champions